# Generated by Django 5.2.4 on 2025-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField()),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
